/**
 * Fetch 2D structure images from PubChem for all matched compounds.
 *
 * Reads the CID map generated by enrich-molecular-data.ts, fetches the PNG
 * from PubChem's PUG REST API, and stores locally under public/structures/.
 *
 * Usage:
 *   npx tsx scripts/fetch-structures.ts
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

const CIDS_PATH = path.resolve(__dirname, 'pubchem-cids.json');
const STRUCTURES_DIR = path.resolve(__dirname, '../public/structures');
const MISSES_PATH = path.resolve(__dirname, 'pubchem-structure-misses.log');
const LOG_PATH = path.resolve(__dirname, 'pubchem-structures.log');

const REQUEST_DELAY_MS = 250; // ~4 req/s

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchStructureImage(productId: string, cid: number): Promise<boolean> {
  const url = `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${cid}/PNG`;

  try {
    const res = await fetch(url);

    if (!res.ok) {
      console.warn(`   ⚠ HTTP ${res.status} for ${productId} (CID ${cid})`);
      return false;
    }

    const buffer = Buffer.from(await res.arrayBuffer());
    const safeId = productId.replace(/[\\/]/g, '_');
    const dest = path.join(STRUCTURES_DIR, `${safeId}.png`);
    fs.writeFileSync(dest, buffer);

    const sizeKb = (buffer.length / 1024).toFixed(1);
    console.log(`   ✓ ${productId} (CID ${cid}) — ${sizeKb} KB`);
    return true;
  } catch (err) {
    console.warn(`   ⚠ Network error for ${productId} (CID ${cid}): ${err}`);
    return false;
  }
}

async function main() {
  console.log('🧪 Fetching 2D structure images from PubChem...\n');

  // Ensure output directory exists
  fs.mkdirSync(STRUCTURES_DIR, { recursive: true });

  // Read CID map
  if (!fs.existsSync(CIDS_PATH)) {
    console.error('❌ CID map not found. Run scripts/enrich-molecular-data.ts first.');
    process.exit(1);
  }
  const cidMap: Record<string, number> = JSON.parse(fs.readFileSync(CIDS_PATH, 'utf-8'));

  const entries = Object.entries(cidMap);
  console.log(`   ${entries.length} compounds to fetch\n`);

  const logLines: string[] = [];
  const misses: string[] = [];
  let successCount = 0;
  let failCount = 0;

  for (let i = 0; i < entries.length; i++) {
    const [productId, cid] = entries[i];

    if ((i + 1) % 50 === 0) {
      console.log(`   Progress: ${i + 1}/${entries.length} images...`);
    }

    const ok = await fetchStructureImage(productId, cid);
    if (ok) {
      successCount++;
      logLines.push(`[OK] ${productId} (CID ${cid})`);
    } else {
      failCount++;
      logLines.push(`[FAIL] ${productId} (CID ${cid})`);
      misses.push(`${productId} | CID ${cid}`);
    }

    await sleep(REQUEST_DELAY_MS);
  }

  // ── Write log ──
  const fullLog = [
    `PS Laboratories Structure Image Fetch — ${new Date().toISOString()}`,
    `Total CID entries: ${entries.length}`,
    `Successfully fetched: ${successCount}`,
    `Failed: ${failCount}`,
    ``,
    `=== RESULTS ===`,
    ``,
    ...logLines,
  ].join('\n');
  fs.writeFileSync(LOG_PATH, fullLog, 'utf-8');

  // ── Write misses ──
  if (misses.length > 0) {
    const missLines = [
      `PS Laboratories Structure Image Fetch — Misses`,
      `Generated: ${new Date().toISOString()}`,
      ``,
      `=== FAILED FETCHES ===`,
      ``,
      ...misses,
    ].join('\n');
    fs.writeFileSync(MISSES_PATH, missLines, 'utf-8');
  }

  console.log(`\n✅ Structure fetch complete.`);
  console.log(`   Successfully fetched: ${successCount}`);
  console.log(`   Failed:               ${failCount}`);
  console.log(`\n📝 Log written to: scripts/pubchem-structures.log`);
  if (failCount > 0) {
    console.log(`📝 Misses written to: scripts/pubchem-structure-misses.log`);
  }
}

main();
